
// Path: /login/ API1

POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

// Path: /states/ API2

GET http://localhost:3000/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzUxODUzODc5fQ.Y8ch8ig5XtYsQkgqKbn36b3a0sejdKcYQ-q2eay702M




###
GET http://localhost:3000/states/22/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzUxODUzODc5fQ.Y8ch8ig5XtYsQkgqKbn36b3a0sejdKcYQ-q2eay702M

// API5

GET http://localhost:3000/districts/3/



POST http://localhost:3000/districts/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzUxODU1MjQ3fQ.xI00heVootB_CQRHy907xV4aiCUcjA9miuhxDMjw1Sg
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

// Path: /districts/:districtId/(API6)

DELETE http://localhost:3000/districts/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzUxODUzODc5fQ.Y8ch8ig5XtYsQkgqKbn36b3a0sejdKcYQ-q2eay702M




PUT http://localhost:3000/districts/5/
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

Path: /states/:stateId/stats/(API8)

GET http://localhost:3000/states/3/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzUxODUzODc5fQ.Y8ch8ig5XtYsQkgqKbn36b3a0sejdKcYQ-q2eay702M